"""GUI 崩溃自愈: 登录自启之外的第二层守护。

原理: 每 5 分钟的计划任务检查 GUI 是否存活, 不在则拉起(--minimized)。
- 仅 frozen + Windows 安装版启用(便携版/开发模式跳过)
- 与 GUI 同为用户权限, 不需要管理员
- 通过互斥的锁文件判定存活(与单实例锁同目录不同名, 避免冲突)

两类标记(均在配置目录):
- gui.alive      GUI 心跳, 启动与每 5 分钟 touch; 超过 10 分钟未更新视为死亡
- watchdog.pause 更新前写入: 安装器覆写 exe 期间看护任务必须按兵不动,
                 否则会把写了一半的 exe 拉起来(Failed to load Python DLL)。
                 带独立 TTL, 更新失败没人清除时 15 分钟后自动恢复守护。

注册方式(v1.25.4 重写): 早期的实现把整段脚本塞进
`powershell -Command "... -Command \"<脚本>\""` 两层引号里再交给 schtasks。
PowerShell 不认 `\\"` 转义, 该命令在解析阶段就整个失败(退出码 -1, 无任何输出),
于是计划任务从未被创建 —— 看护功能自 v1.24.0 起实际是空转的。
另一个坑是 schtasks `/TR` 上限 261 字符, 而脚本本身就有 ~400 字符。

现在改为: 脚本落盘为 <配置目录>/watchdog.ps1, 任务动作只用短串
`powershell -File "<脚本>"` 引用它, 且 schtasks 由 Python 直接以 argv 调起,
中间不再经过任何 shell —— 引号只被解析一次。
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

TASK = "ZJUAutoLogin-Watchdog"
SCRIPT_NAME = "watchdog.ps1"
ALIVE_STALE_MIN = 10   # 心跳超过该分钟数 → GUI 视为死亡
PAUSE_TTL_MIN = 15     # 暂停标记超过该分钟数 → 自动失效(防更新失败后守护永久关闭)
MAX_TASK_ACTION = 261  # schtasks /TR 硬上限, 超出必然注册失败


def _enabled() -> bool:
    return sys.platform == "win32" and getattr(sys, "frozen", False)


def _marker_path(name: str) -> Path:
    from .config import config_dir
    return config_dir() / name


def _ps_str(value: object) -> str:
    """PowerShell 单引号字符串: 路径含 ' 时写成 '' 才不会被截断。"""
    return "'" + str(value).replace("'", "''") + "'"


def _ps_script() -> str:
    """看护脚本正文: 心跳新鲜 或 暂停标记未过期 时绝不拉起。"""
    alive = _ps_str(_marker_path("gui.alive"))
    pause = _ps_str(_marker_path("watchdog.pause"))
    exe = _ps_str(sys.executable)
    return (
        "# ZJU AutoLogin GUI watchdog - generated by the app, safe to delete.\n"
        f"$a={alive}; $p={pause}; "
        "$f=(Test-Path $a) -and (((Get-Date)-(Get-Item $a).LastWriteTime).TotalMinutes -le "
        f"{ALIVE_STALE_MIN}); "
        "$u=(Test-Path $p) -and (((Get-Date)-(Get-Item $p).LastWriteTime).TotalMinutes -le "
        f"{PAUSE_TTL_MIN}); "
        f"if (-not $f -and -not $u) {{ Start-Process {exe} -ArgumentList '--minimized' }}\n"
    )


def script_path() -> Path:
    return _marker_path(SCRIPT_NAME)


def write_script() -> Path | None:
    """脚本落盘; 失败返回 None(此时不能注册任务, 否则任务会指向空文件)。"""
    path = script_path()
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        # utf-8-sig: PowerShell 5.1 读无 BOM 的 UTF-8 会按 ANSI 解, 用户名含中文时路径会乱码
        path.write_text(_ps_script(), encoding="utf-8-sig")
        return path
    except OSError:
        return None


def task_action(script: Path | None = None) -> str:
    return ('powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass '
            f'-File "{script or script_path()}"')


def install() -> bool:
    """注册轻量看护计划任务(每 5 分钟); 幂等, 已存在则原地覆盖。"""
    if not _enabled():
        return False
    import subprocess

    script = write_script()
    if script is None:
        return False
    action = task_action(script)
    if len(action) > MAX_TASK_ACTION:
        return False
    try:
        r = subprocess.run(
            ["schtasks", "/Create", "/F", "/TN", TASK, "/SC", "MINUTE", "/MO", "5",
             "/RL", "LIMITED", "/TR", action],
            capture_output=True, timeout=30,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        return r.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def is_installed() -> bool:
    if not _enabled():
        return False
    import subprocess

    try:
        r = subprocess.run(["schtasks", "/Query", "/TN", TASK],
                           capture_output=True, timeout=15,
                           creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        return r.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def refresh_if_installed() -> bool:
    """任务已存在则用当前脚本重建(向存量机器铺新判断逻辑); 未安装不创建。"""
    if not _enabled():
        return False
    if not is_installed():
        # 早期版本注册命令被引号解析吃掉, 任务根本没建成; 顺手把脚本补上,
        # 真正的注册交给调用方(需先确认用户确实开着系统级保活)。
        write_script()
        return False
    return install()


def uninstall() -> bool:
    if not _enabled():
        return False
    import subprocess

    try:
        r = subprocess.run(["schtasks", "/Delete", "/F", "/TN", TASK],
                           capture_output=True, timeout=30,
                           creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    except (OSError, subprocess.TimeoutExpired):
        return False
    if r.returncode != 0:
        return False
    try:
        script_path().unlink(missing_ok=True)
    except OSError:
        pass
    return True


def touch_alive() -> None:
    """GUI 心跳: 启动与每 5 分钟更新存活标记(必须短于 ALIVE_STALE_MIN)。"""
    if not _enabled():
        return
    try:
        path = _marker_path("gui.alive")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(str(os.getpid()), encoding="ascii")
    except OSError:
        pass


def pause_for_update() -> None:
    """更新前调用: 安装器覆写 exe 期间看护任务不拉起(TTL 自动失效兜底)。"""
    if not _enabled():
        return
    try:
        path = _marker_path("watchdog.pause")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(str(os.getpid()), encoding="ascii")
    except OSError:
        pass


def resume() -> None:
    """GUI 启动时调用: 上轮更新已结束, 清除暂停标记恢复守护。"""
    try:
        _marker_path("watchdog.pause").unlink(missing_ok=True)
    except OSError:
        pass
